### ISSUE TITLE
[FEAT] Lottie spm 설치

### ISSUE THREAD

**Issue by deslog** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80#47]
## 🔵 Lottie를 Swift Package Manager로 추가합니다.

우리의 🎨**디자이너 베리**🍓가 그려준 GIF 파일을 로드하기 위한 라이브러리입니다.

![제목_없는_아트워크](https://user-images.githubusercontent.com/96969693/198925032-b16ae0c5-ea6b-4103-8a5a-22c0dabcee33.gif)

## 🔵 관련 이슈
- 관련 이슈 없음 

## 🔵 레퍼런스
- 관련 레퍼런스 없음

**Comment by YoonAh-dev** [comment]
[`9d5f23e`](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80/commit/9d5f23e09371cdf893c8caf9bbc3e7844d8eb1ce) 요거는 cache를 위해서 만든 코드라서 크게 상관없고, [`2d8118c`](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80/commit/2d8118c3fc0bdb282314e68f97a8af9dc3d407c0) 이 부분이 .gitignore과 함께 했을 때.. 에러 놈을 죽일 수 있었습니다.

더 좋은 설명을 위해 [2차 전쟁 발발](https://yxxnaxxin.notion.site/Github-Action-with-SPM-2-c4915eeda5f14b03b7b0a98f8fc0ce9f)글로 다시 돌아오겠습니다.

**Comment by deslog** [comment]
> [`9d5f23e`](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80/commit/9d5f23e09371cdf893c8caf9bbc3e7844d8eb1ce) 요거는 cache를 위해서 만든 코드라서 크게 상관없고, [`2d8118c`](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-EarthValley80/commit/2d8118c3fc0bdb282314e68f97a8af9dc3d407c0) 이 부분이 .gitignore과 함께 했을 때.. 에러 놈을 죽일 수 있었습니다.
> 
> 더 좋은 설명을 위해 [2차 전쟁 발발](https://yxxnaxxin.notion.site/Github-Action-with-SPM-2-c4915eeda5f14b03b7b0a98f8fc0ce9f)글로 다시 돌아오겠습니다.. 다 쓰면 discussion에 게시하겠읍니다..

듀나멋저!!!!!!!!
