### ISSUE TITLE
[DOCS] Builder에서 clean 부분 삭제

### ISSUE THREAD

**Issue by YoonAh-dev** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80#68]
## 🔵 story를 적어주세요

Builder에서 clean 코드 때문에 액션을 돌리는 시간이 너무 깁니다..

## 🔵 완료 조건
- [ ]  clean 부분 삭제 

## 🔵 관련 이슈
- 관련 이슈 없음

## 🔵 레퍼런스
- 관련 레퍼런스 없음

**Comment by deslog** [comment]
기다리다가 지치셨군요,,🫢

**Comment by YoonAh-dev** [comment]
@deslog 화가 잔뜩 났습니다.......
